# Sysdig 활동 감사 (Activity Audit) 설정
# Voting App의 모든 보안 관련 활동을 추적하고 감사

apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-activity-audit
  namespace: voting-app
  annotations:
    sysdig.com/policy-zone: "voting-app-zone"
data:
  # 감사 정책 설정
  audit-policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    metadata:
      name: voting-app-audit-policy
    rules:
      # 1. 네임스페이스 수준 감사
      - level: Metadata
        namespaces: ["voting-app"]
        resources:
        - group: ""
          resources: ["pods", "services", "configmaps", "secrets"]
        - group: "apps"
          resources: ["deployments", "replicasets"]
        - group: "networking.k8s.io"
          resources: ["networkpolicies"]
        
      # 2. 보안 관련 리소스 상세 감사
      - level: RequestResponse
        namespaces: ["voting-app"]
        resources:
        - group: ""
          resources: ["secrets"]
        - group: "rbac.authorization.k8s.io"
          resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
        
      # 3. 파드 실행 및 수정 감사
      - level: Request
        namespaces: ["voting-app"]
        resources:
        - group: ""
          resources: ["pods/exec", "pods/attach", "pods/portforward"]
        
      # 4. 서비스 어카운트 관련 감사
      - level: Metadata
        namespaces: ["voting-app"]
        resources:
        - group: ""
          resources: ["serviceaccounts"]
        
      # 5. 보안 컨텍스트 변경 감사
      - level: Request
        namespaces: ["voting-app"]
        resources:
        - group: "policy"
          resources: ["podsecuritypolicies"]

  # 감사 로그 수집 설정
  audit-log-collection.yaml: |
    apiVersion: logging.coreos.com/v1
    kind: ClusterLogForwarder
    metadata:
      name: voting-app-audit-logs
    spec:
      outputs:
      - name: sysdig-audit-output
        type: sysdig
        sysdig:
          token: "${SYSDIG_SECURE_API_TOKEN}"
          endpoint: "${SYSDIG_SECURE_ENDPOINT}"
          
      inputs:
      - name: audit-logs
        application:
          namespaces: ["voting-app"]
          
      pipelines:
      - name: audit-pipeline
        inputRefs:
        - audit-logs
        outputRefs:
        - sysdig-audit-output
        labels:
          app: "voting-app"
          audit: "true"

  # 사용자 활동 추적 설정
  user-activity-tracking.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: user-activity-tracking
    data:
      tracking-rules.yaml: |
        # 사용자 활동 추적 규칙
        rules:
          # 1. kubectl 명령 추적
          - name: "kubectl-commands"
            description: "kubectl 명령어 실행 추적"
            events:
              - "kubectl.create"
              - "kubectl.delete"
              - "kubectl.apply"
              - "kubectl.exec"
              - "kubectl.port-forward"
            attributes:
              - "user.name"
              - "user.groups"
              - "k8s.namespace"
              - "k8s.resource.type"
              - "k8s.resource.name"
              - "command.line"
              - "timestamp"
            
          # 2. 파드 접근 추적
          - name: "pod-access"
            description: "파드 직접 접근 추적"
            events:
              - "pod.exec"
              - "pod.attach"
              - "pod.port-forward"
            attributes:
              - "user.name"
              - "pod.name"
              - "pod.namespace"
              - "container.name"
              - "command.executed"
              - "session.duration"
              - "timestamp"
            
          # 3. 시크릿 접근 추적
          - name: "secret-access"
            description: "시크릿 리소스 접근 추적"
            events:
              - "secret.read"
              - "secret.create"
              - "secret.update"
              - "secret.delete"
            attributes:
              - "user.name"
              - "secret.name"
              - "secret.namespace"
              - "access.type"
              - "timestamp"
            
          # 4. 네트워크 정책 변경 추적
          - name: "network-policy-changes"
            description: "네트워크 정책 변경 추적"
            events:
              - "networkpolicy.create"
              - "networkpolicy.update"
              - "networkpolicy.delete"
            attributes:
              - "user.name"
              - "policy.name"
              - "policy.namespace"
              - "change.type"
              - "policy.rules"
              - "timestamp"

  # 시스템 변경 감사 설정
  system-change-audit.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: system-change-audit
    data:
      change-tracking.yaml: |
        # 시스템 변경 사항 추적
        categories:
          # 1. 인프라 변경
          infrastructure:
            - name: "deployment-changes"
              description: "배포 설정 변경"
              resources: ["deployments", "replicasets", "daemonsets"]
              events: ["create", "update", "delete", "scale"]
              
            - name: "service-changes"
              description: "서비스 설정 변경"
              resources: ["services", "ingresses"]
              events: ["create", "update", "delete"]
              
            - name: "configmap-changes"
              description: "설정 변경"
              resources: ["configmaps"]
              events: ["create", "update", "delete"]
          
          # 2. 보안 설정 변경
          security:
            - name: "rbac-changes"
              description: "RBAC 설정 변경"
              resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
              events: ["create", "update", "delete"]
              
            - name: "security-policy-changes"
              description: "보안 정책 변경"
              resources: ["podsecuritypolicies", "networkpolicies"]
              events: ["create", "update", "delete"]
              
            - name: "serviceaccount-changes"
              description: "서비스 어카운트 변경"
              resources: ["serviceaccounts"]
              events: ["create", "update", "delete"]
          
          # 3. 데이터 접근
          data_access:
            - name: "persistent-volume-access"
              description: "영구 볼륨 접근"
              resources: ["persistentvolumes", "persistentvolumeclaims"]
              events: ["create", "update", "delete", "mount", "unmount"]
              
            - name: "secret-access"
              description: "시크릿 접근"
              resources: ["secrets"]
              events: ["create", "read", "update", "delete"]

  # 감사 리포트 설정
  audit-reporting.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: audit-reporting
    data:
      report-config.yaml: |
        # 감사 리포트 설정
        reports:
          # 1. 일일 활동 요약
          daily_summary:
            name: "Daily Activity Summary"
            description: "일일 사용자 및 시스템 활동 요약"
            frequency: "daily"
            time: "09:00"
            format: ["json", "pdf"]
            recipients: ["security-team@company.com"]
            content:
              - "user_activity_summary"
              - "system_changes"
              - "security_events"
              - "policy_violations"
            
          # 2. 주간 보안 리포트
          weekly_security:
            name: "Weekly Security Report"
            description: "주간 보안 활동 및 위협 분석"
            frequency: "weekly"
            day: "monday"
            time: "08:00"
            format: ["pdf", "html"]
            recipients: ["security-team@company.com", "devops-team@company.com"]
            content:
              - "threat_analysis"
              - "vulnerability_summary"
              - "compliance_status"
              - "incident_summary"
            
          # 3. 월간 컴플라이언스 리포트
          monthly_compliance:
            name: "Monthly Compliance Report"
            description: "월간 컴플라이언스 상태 및 감사 결과"
            frequency: "monthly"
            day: 1
            time: "07:00"
            format: ["pdf", "csv"]
            recipients: ["compliance-team@company.com", "audit-team@company.com"]
            content:
              - "compliance_metrics"
              - "audit_findings"
              - "remediation_status"
              - "risk_assessment"

  # 알림 및 경고 설정
  alert-configuration.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: audit-alerts
    data:
      alert-rules.yaml: |
        # 감사 관련 알림 규칙
        alerts:
          # 1. 높은 위험도 활동
          high_risk_activity:
            name: "High Risk Activity Detected"
            description: "높은 위험도 활동 탐지"
            severity: "critical"
            conditions:
              - "privilege_escalation_attempt"
              - "unauthorized_secret_access"
              - "suspicious_network_activity"
              - "container_escape_attempt"
            notifications:
              - type: "email"
                recipients: ["security-team@company.com", "incident-response@company.com"]
              - type: "slack"
                channel: "#security-alerts"
              - type: "pagerduty"
                service: "security-incidents"
            
          # 2. 컴플라이언스 위반
          compliance_violation:
            name: "Compliance Violation"
            description: "컴플라이언스 정책 위반"
            severity: "high"
            conditions:
              - "cis_benchmark_violation"
              - "nist_framework_violation"
              - "policy_exception"
            notifications:
              - type: "email"
                recipients: ["compliance-team@company.com"]
              - type: "slack"
                channel: "#compliance-alerts"
            
          # 3. 비정상적인 사용자 활동
          anomalous_user_activity:
            name: "Anomalous User Activity"
            description: "비정상적인 사용자 활동 패턴"
            severity: "medium"
            conditions:
              - "unusual_access_pattern"
              - "off_hours_activity"
              - "multiple_failed_attempts"
            notifications:
              - type: "email"
                recipients: ["security-team@company.com"]
              - type: "slack"
                channel: "#security-monitoring"

---
# 감사 로그 저장을 위한 PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-logs-pvc
  namespace: voting-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
# 감사 로그 수집을 위한 DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: audit-log-collector
  namespace: voting-app
  labels:
    app: audit-log-collector
spec:
  selector:
    matchLabels:
      app: audit-log-collector
  template:
    metadata:
      labels:
        app: audit-log-collector
    spec:
      serviceAccountName: audit-log-collector
      containers:
      - name: log-collector
        image: sysdig/sysdig-audit-collector:latest
        env:
        - name: SYSDIG_SECURE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: sysdig-credentials
              key: api-token
        - name: SYSDIG_SECURE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: sysdig-credentials
              key: endpoint
        volumeMounts:
        - name: audit-logs
          mountPath: /var/log/audit
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        - name: host-sys
          mountPath: /host/sys
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: audit-logs
        persistentVolumeClaim:
          claimName: audit-logs-pvc
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-sys
        hostPath:
          path: /sys
      hostNetwork: true
      hostPID: true
