name: Sysdig Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # 매일 오전 2시 (UTC) 정기 스캔
    - cron: '0 2 * * *'

env:
  REGISTRY: ghcr.io
  SYSDIG_SECURE_ENDPOINT: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
  SYSDIG_SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}

jobs:
  # IaC 보안 스캔 (공식 문서 기반 올바른 설정)
  iac-scan:
    name: Sysdig IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Sysdig IaC Scan
        uses: sysdiglabs/scan-action@v6
        with:
          # 공식 문서 기반 올바른 IaC 스캔 설정
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: iac
          iac-scan-path: ./k8s-specifications
          recursive: true
          minimum-severity: medium
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false

      - name: Upload IaC Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-iac-results
          path: |
            sysdig-results.*
            scan-result.json

  # Vote 서비스 빌드 및 스캔
  vote-build-scan:
    name: Vote Service - Build and Scan
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image locally (for scanning)
        id: build-local
        run: |
          # 로컬에서 이미지 빌드 (스캔용)
          docker build -t vote-local:${{ github.sha }} ./vote --target final
          echo "local-image=vote-local:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Run Sysdig Secure Scan (Local Image)
        uses: sysdiglabs/scan-action@v6
        with:
          # 로컬 빌드된 이미지 스캔
          image-tag: ${{ steps.build-local.outputs.local-image }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: vm
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false
          use-policies: true
          severity-at-least: medium

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Extract metadata (for registry push)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/vote
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image to registry
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: ./vote
          target: final
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # v6의 새로운 기능들
          provenance: true
          sbom: true
          platforms: linux/amd64,linux/arm64

      - name: Output final image
        id: image
        run: |
          echo "image=${{ env.REGISTRY }}/${{ github.repository }}/vote:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload Vote Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-vote-results
          path: |
            sysdig-results.*
            scan-result.json
            sarif.json

  # Worker 서비스 빌드 및 스캔
  worker-build-scan:
    name: Worker Service - Build and Scan
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image locally (for scanning)
        id: build-local
        run: |
          # 로컬에서 이미지 빌드 (스캔용)
          docker build -t worker-local:${{ github.sha }} ./worker
          echo "local-image=worker-local:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Run Sysdig Secure Scan (Local Image)
        uses: sysdiglabs/scan-action@v6
        with:
          # 로컬 빌드된 이미지 스캔
          image-tag: ${{ steps.build-local.outputs.local-image }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: vm
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false
          use-policies: true
          severity-at-least: medium

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Extract metadata (for registry push)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/worker
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image to registry
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # v6의 새로운 기능들
          provenance: true
          sbom: true
          platforms: linux/amd64,linux/arm64

      - name: Output final image
        id: image
        run: |
          echo "image=${{ env.REGISTRY }}/${{ github.repository }}/worker:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload Worker Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-worker-results
          path: |
            sysdig-results.*
            scan-result.json
            sarif.json

  # Result 서비스 빌드 및 스캔
  result-build-scan:
    name: Result Service - Build and Scan
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image locally (for scanning)
        id: build-local
        run: |
          # 로컬에서 이미지 빌드 (스캔용)
          docker build -t result-local:${{ github.sha }} ./result
          echo "local-image=result-local:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Run Sysdig Secure Scan (Local Image)
        uses: sysdiglabs/scan-action@v6
        with:
          # 로컬 빌드된 이미지 스캔
          image-tag: ${{ steps.build-local.outputs.local-image }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: vm
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false
          use-policies: true
          severity-at-least: medium

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Extract metadata (for registry push)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/result
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image to registry
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: ./result
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # v6의 새로운 기능들
          provenance: true
          sbom: true
          platforms: linux/amd64,linux/arm64

      - name: Output final image
        id: image
        run: |
          echo "image=${{ env.REGISTRY }}/${{ github.repository }}/result:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload Result Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-result-results
          path: |
            sysdig-results.*
            scan-result.json
            sarif.json

  # Sysdig 전용 보안 분석 및 리포트
  sysdig-security-analysis:
    name: Sysdig Security Analysis & Report
    runs-on: ubuntu-latest
    needs: [iac-scan, vote-build-scan, worker-build-scan, result-build-scan]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all Sysdig scan results
        uses: actions/download-artifact@v4
        with:
          path: ./sysdig-results/

      - name: Generate Sysdig-focused Security Report
        run: |
          echo "# 🔒 Sysdig v6 보안 스캔 결과 리포트 (이미지 접근 문제 해결)" > sysdig-security-report.md
          echo "" >> sysdig-security-report.md
          echo "## 📊 스캔 개요" >> sysdig-security-report.md
          echo "- **스캔 일시**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> sysdig-security-report.md
          echo "- **커밋 SHA**: ${{ github.sha }}" >> sysdig-security-report.md
          echo "- **브랜치**: ${{ github.ref_name }}" >> sysdig-security-report.md
          echo "- **Sysdig Scan Action**: v6 (로컬 이미지 스캔)" >> sysdig-security-report.md
          echo "" >> sysdig-security-report.md
          echo "## 🔧 이미지 접근 문제 해결" >> sysdig-security-report.md
          echo "### 이전 문제점" >> sysdig-security-report.md
          echo "- ❌ **레지스트리 이미지 스캔**: 이미지가 아직 푸시되지 않아 접근 불가" >> sysdig-security-report.md
          echo "- ❌ **Unable to get image**: 레지스트리에서 이미지를 가져올 수 없음" >> sysdig-security-report.md
          echo "" >> sysdig-security-report.md
          echo "### 해결 방법" >> sysdig-security-report.md
          echo "- ✅ **로컬 이미지 빌드**: docker build로 로컬에 이미지 생성" >> sysdig-security-report.md
          echo "- ✅ **로컬 이미지 스캔**: 로컬에 있는 이미지를 직접 스캔" >> sysdig-security-report.md
          echo "- ✅ **스캔 후 푸시**: 스캔 완료 후 레지스트리에 푸시" >> sysdig-security-report.md
          echo "" >> sysdig-security-report.md
          echo "## 🏗️ 수정된 스캔 프로세스" >> sysdig-security-report.md
          echo "### 1. **IaC 스캔**" >> sysdig-security-report.md
          echo "   - 📁 **스캔 경로**: ./k8s-specifications/" >> sysdig-security-report.md
          echo "   - 🔄 **재귀 스캔**: 활성화" >> sysdig-security-report.md
          echo "   - ⚠️ **최소 심각도**: Medium 이상" >> sysdig-security-report.md
          echo "" >> sysdig-security-report.md
          echo "### 2. **컨테이너 이미지 스캔 (로컬 빌드)**" >> sysdig-security-report.md
          echo "   - 🐍 **Vote 서비스**: vote-local:${{ github.sha }}" >> sysdig-security-report.md
          echo "   - ⚙️ **Worker 서비스**: worker-local:${{ github.sha }}" >> sysdig-security-report.md
          echo "   - 📊 **Result 서비스**: result-local:${{ github.sha }}" >> sysdig-security-report.md
          echo "" >> sysdig-security-report.md
          echo "### 3. **레지스트리 푸시 (스캔 후)**" >> sysdig-security-report.md
          echo "   - 🚀 Multi-platform 빌드 (AMD64, ARM64)" >> sysdig-security-report.md
          echo "   - 📋 SBOM 및 Provenance 생성" >> sysdig-security-report.md
          echo "   - 🏷️ 적절한 태그 및 라벨 적용" >> sysdig-security-report.md
          echo "" >> sysdig-security-report.md
          echo "## 📋 스캔 결과 파일" >> sysdig-security-report.md
          echo "### IaC 스캔 결과" >> sysdig-security-report.md
          if [ -d "./sysdig-results/sysdig-iac-results" ]; then
            echo "- ✅ IaC 보안 스캔 완료 (k8s-specifications 재귀 스캔)" >> sysdig-security-report.md
          fi
          echo "" >> sysdig-security-report.md
          echo "### 컨테이너 이미지 스캔 결과" >> sysdig-security-report.md
          if [ -d "./sysdig-results/sysdig-vote-results" ]; then
            echo "- ✅ Vote 서비스 스캔 완료 (로컬 이미지)" >> sysdig-security-report.md
          fi
          if [ -d "./sysdig-results/sysdig-worker-results" ]; then
            echo "- ✅ Worker 서비스 스캔 완료 (로컬 이미지)" >> sysdig-security-report.md
          fi
          if [ -d "./sysdig-results/sysdig-result-results" ]; then
            echo "- ✅ Result 서비스 스캔 완료 (로컬 이미지)" >> sysdig-security-report.md
          fi
          echo "" >> sysdig-security-report.md
          echo "## 🎯 다음 단계" >> sysdig-security-report.md
          echo "1. **Sysdig Secure 콘솔**에서 상세 취약점 분석 확인" >> sysdig-security-report.md
          echo "2. **GitHub Security 탭**에서 SARIF 결과 검토" >> sysdig-security-report.md
          echo "3. **Medium 이상 취약점** 우선 수정" >> sysdig-security-report.md
          echo "4. **IaC 정책 위반** 사항 개선" >> sysdig-security-report.md
          echo "5. **로컬 스캔 결과**를 바탕으로 보안 개선" >> sysdig-security-report.md

      - name: Upload Sysdig Security Report
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-security-report
          path: sysdig-security-report.md

      - name: Comment PR with Sysdig Report
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('sysdig-security-report.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });

  # Sysdig 메트릭 수집
  sysdig-metrics:
    name: Sysdig Security Metrics
    runs-on: ubuntu-latest
    needs: [sysdig-security-analysis]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Collect Sysdig Metrics
        run: |
          echo "# 📊 Sysdig 보안 메트릭 (로컬 이미지 스캔)" > sysdig-metrics.md
          echo "- **스캔 완료 시간**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> sysdig-metrics.md
          echo "- **Sysdig 버전**: v6 (로컬 이미지 스캔)" >> sysdig-metrics.md
          echo "- **스캔된 이미지**: 3개 (로컬 빌드)" >> sysdig-metrics.md
          echo "- **IaC 스캔**: ✅ 완료 (./k8s-specifications, 재귀)" >> sysdig-metrics.md
          echo "- **SARIF 업로드**: ✅ 완료 (올바른 경로)" >> sysdig-metrics.md
          echo "- **SBOM 생성**: ✅ 완료" >> sysdig-metrics.md
          echo "- **Multi-platform 빌드**: ✅ 완료 (AMD64, ARM64)" >> sysdig-metrics.md
          echo "- **이미지 접근 문제**: ✅ 해결 (로컬 빌드 방식)" >> sysdig-metrics.md
          echo "" >> sysdig-metrics.md
          echo "## 🎯 로컬 이미지 스캔의 장점" >> sysdig-metrics.md
          echo "1. **즉시 스캔**: 레지스트리 푸시 전에 보안 검증" >> sysdig-security-report.md
          echo "2. **접근 문제 해결**: 로컬 이미지로 접근 오류 방지" >> sysdig-metrics.md
          echo "3. **빠른 피드백**: 빌드 직후 즉시 보안 결과 확인" >> sysdig-metrics.md
          echo "4. **안전한 푸시**: 스캔 완료 후에만 레지스트리에 푸시" >> sysdig-metrics.md

      - name: Upload Sysdig Metrics
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-metrics
          path: sysdig-metrics.md
