name: Sysdig Security Scan (Official Style)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  # IaC 보안 스캔
  iac-scan:
    name: Sysdig IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Sysdig IaC Scan
        id: iac-scan
        uses: sysdiglabs/scan-action@v6
        with:
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: iac
          iac-scan-path: ./k8s-specifications
          recursive: true
          minimum-severity: medium
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false

      - name: Upload IaC SARIF to GitHub
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Upload IaC Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-iac-results
          path: |
            sarif.json
            scan-result.json
          if-no-files-found: warn

  # Vote 서비스 빌드 및 스캔
  vote-build-scan:
    name: Vote Service - Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        run: |
          echo "Building vote image..."
          docker build -t vote-local:${{ github.sha }} ./vote --target final
          docker images | grep vote-local

      - name: Scan Vote Image
        id: scan
        uses: sysdiglabs/scan-action@v6
        with:
          image-tag: vote-local:${{ github.sha }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: vm
          severity-at-least: medium
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false

      - name: Upload Vote SARIF to GitHub
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Upload Vote Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-vote-results
          path: |
            sarif.json
            scan-result.json
          if-no-files-found: warn

  # Worker 서비스 빌드 및 스캔
  worker-build-scan:
    name: Worker Service - Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        run: |
          echo "Building worker image..."
          docker build -t worker-local:${{ github.sha }} ./worker
          docker images | grep worker-local

      - name: Scan Worker Image
        id: scan
        uses: sysdiglabs/scan-action@v6
        with:
          image-tag: worker-local:${{ github.sha }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: vm
          severity-at-least: medium
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false

      - name: Upload Worker SARIF to GitHub
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Upload Worker Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-worker-results
          path: |
            sarif.json
            scan-result.json
          if-no-files-found: warn

  # Result 서비스 빌드 및 스캔
  result-build-scan:
    name: Result Service - Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        run: |
          echo "Building result image..."
          docker build -t result-local:${{ github.sha }} ./result
          docker images | grep result-local

      - name: Scan Result Image
        id: scan
        uses: sysdiglabs/scan-action@v6
        with:
          image-tag: result-local:${{ github.sha }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: vm
          severity-at-least: medium
          stop-on-failed-policy-eval: false
          stop-on-processing-error: false

      - name: Upload Result SARIF to GitHub
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Upload Result Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-result-results
          path: |
            sarif.json
            scan-result.json
          if-no-files-found: warn
